Repository open-company/open-company-storage, pull requests merged in 2018-11, with the labels that each got.

#166 No version update when sharing a post
  src/oc/storage/api/entries.clj
  src/oc/storage/resources/entry.clj
Labels: reviewing

#168 Fix duplicated share [WIP]
  project.clj
  src/oc/storage/api/activity.clj
  src/oc/storage/api/boards.clj
  src/oc/storage/api/entries.clj
  src/oc/storage/api/orgs.clj
Labels: ready for deploy

#169 Fix shared limit
  src/oc/storage/api/entries.clj
Labels: URGENT, reviewing

#172 Better use of `api-common/rep`
  src/oc/storage/api/boards.clj
  src/oc/storage/api/entries.clj
Labels: reviewing

#170 Cut shared lists
  project.clj
  src/oc/storage/resources/maintenance.clj
Labels: reviewing

#173 Remove initial NUX draft post. Wasn't getting used.
  project.clj
  resources/samples/drafts.edn
  src/oc/storage/api/orgs.clj
  src/oc/storage/config.clj
Labels: reviewing

#174 Digest tweaks
  src/oc/storage/async/email.clj
Labels: ready for deploy

#175 Update dependencies.
  project.clj
  src/oc/storage/resources/org.clj
Labels: reviewing
