Repository open-company/open-company-storage, pull requests merged in 2018-12, with the labels that each got.

#176 Auth lib
  project.clj
  src/oc/storage/api/videos.clj
  src/oc/storage/auth.clj
Labels: ready for deploy

#177 Storage lib
  project.clj
  src/oc/storage/api/access.clj
  src/oc/storage/api/entries.clj
  src/oc/storage/resources/board.clj
Labels: ready for deploy

#178 Use an identity token to allow requests for org information.
  project.clj
  src/oc/storage/api/entry_point.clj
  src/oc/storage/api/orgs.clj
  src/oc/storage/representations/entry.clj
Labels: reviewing

#179 Post link behaviour
  project.clj
  src/oc/storage/api/entry_point.clj
  src/oc/storage/api/orgs.clj
  src/oc/storage/representations/entry.clj
  src/oc/storage/representations/org.clj
Labels: ready for deploy

#180 Fix decode id-token
  project.clj
Labels: ready for review
