Repository open-company/open-company-storage, pull requests merged in 2018-09, with the labels that each got.

#145 Pre-flight check option for board creation.
  oc-storage.paw
  src/oc/storage/api/boards.clj
  src/oc/storage/representations/org.clj
Labels: reviewing

#143 Handle auto share on video processing.
  README.md
  project.clj
  src/oc/storage/api/entries.clj
  src/oc/storage/api/videos.clj
  src/oc/storage/app.clj
  src/oc/storage/auth.clj
Labels: ready for deploy

#142 Revert a post to a specified version number.
  src/oc/storage/api/entries.clj
  src/oc/storage/representations/entry.clj
  src/oc/storage/representations/media_types.clj
  src/oc/storage/resources/entry.clj
Labels: reviewing

#144 NUX sample content
  README.md
  docs/Storage-Schema.svg
  oc-storage.paw
  opt/samples/18F.edn
  opt/samples/green-labs.edn
  opt/samples/read-only.edn
  opt/samples/uni.edn
  project.clj
  resources/default-new-org.edn
  resources/samples/all-hands.edn
  resources/samples/decisions.edn
  resources/samples/design.edn
  resources/samples/drafts.edn
  resources/samples/general.edn
  resources/samples/lessons-learned.edn
  resources/samples/marketing.edn
  resources/samples/mentions.html
  resources/samples/people.edn
  resources/samples/product-updates.edn
  resources/samples/week-in-review.edn
  src/oc/storage/api/boards.clj
  src/oc/storage/api/orgs.clj
  src/oc/storage/async/auth_notification.clj
  src/oc/storage/config.clj
  src/oc/storage/db/migrations/1535717117279_remove_topics.edn
  src/oc/storage/representations/board.clj
  src/oc/storage/representations/entry.clj
  src/oc/storage/representations/media_types.clj
  src/oc/storage/representations/org.clj
  src/oc/storage/resources/board.clj
  src/oc/storage/resources/common.clj
  src/oc/storage/resources/entry.clj
  src/oc/storage/resources/org.clj
  src/oc/storage/util/generate.clj
  test/oc/storage/unit/representations/reactions.clj
Labels: ready for deploy

#146 SNS notification of NUX board selection.
  project.clj
  src/oc/storage/api/orgs.clj
  src/oc/storage/async/notification.clj
Labels: ready for deploy

#147 Pre-flight check update
  src/oc/storage/api/boards.clj
Labels: ready for deploy

#149 People invite broken
  project.clj
  src/oc/storage/api/orgs.clj
Labels: URGENT, ready for deploy

#148 Return new entries on board creation.
  src/oc/storage/api/boards.clj
Labels: ready for review

#151 Filter by board uuid to only return entries for the board created.
  src/oc/storage/api/boards.clj
Labels: reviewing

#152 Notify SNS of initial draft for users.
  project.clj
  src/oc/storage/api/orgs.clj
Labels: ready for deploy
