Repository open-company/open-company-storage, pull requests merged in 2018-10, with the labels that each got.

#153 Ziggeo api error
  src/oc/storage/api/entries.clj
  src/oc/storage/resources/entry.clj
  src/oc/storage/util/ziggeo.clj
Labels: ready for review

#156 NUX video post and min/max sample entries
  project.clj
  resources/samples/all-hands.edn
  resources/samples/decisions.edn
  resources/samples/design.edn
  resources/samples/general.edn
  resources/samples/lessons-learned.edn
  resources/samples/marketing.edn
  resources/samples/people.edn
  resources/samples/product-updates.edn
  resources/samples/week-in-review.edn
  src/oc/storage/api/orgs.clj
  src/oc/storage/async/bot.clj
  src/oc/storage/config.clj
Labels: reviewing

#157 Fix sample posts retrieve.
  src/oc/storage/api/orgs.clj
Labels: URGENT, reviewing

#155 Store video image from Ziggeo
  src/oc/storage/representations/entry.clj
  src/oc/storage/resources/common.clj
  src/oc/storage/resources/entry.clj
Labels: reviewing

#160 Allow us to easily use the REPL for DB access only
  project.clj
  src/dev.clj
  src/oc/storage/components.clj
Labels: ready for deploy

#161 Truncate org slug
  src/oc/storage/resources/org.clj
Labels: ready for review

#158 Strip script tags to prevent xss.
  project.clj
  src/oc/storage/async/bot.clj
  src/oc/storage/async/email.clj
  src/oc/storage/async/notification.clj
  src/oc/storage/resources/board.clj
  src/oc/storage/resources/entry.clj
Labels: ready for deploy

#163 Upgrade oc lib to latest version.
  project.clj
Labels: URGENT, ready for review

#162 Adjust default and available NUX boards.
  src/oc/storage/config.clj
Labels: ready for deploy

#164 Add Must see and Video to digest
  src/oc/storage/async/bot.clj
  src/oc/storage/async/email.clj
Labels: ready for deploy
