Repository open-company/open-company-storage, pull requests merged in 2019-08, with the labels that each got.

#211 Follow-ups
  oc-storage.paw
  project.clj
  resources/ascii_art.txt
  src/oc/storage/api/activity.clj
  src/oc/storage/api/entries.clj
  src/oc/storage/api/orgs.clj
  src/oc/storage/app.clj
  src/oc/storage/async/notification.clj
  src/oc/storage/db/migrations/1562328683815_create_follow_ups_index_map_multi.edn
  src/oc/storage/representations/board.clj
  src/oc/storage/representations/entry.clj
  src/oc/storage/representations/media_types.clj
  src/oc/storage/representations/org.clj
  src/oc/storage/resources/board.clj
  src/oc/storage/resources/common.clj
  src/oc/storage/resources/entry.clj
Labels: ready for deploy

#215 Fix Follow-ups pagination
  src/oc/storage/api/activity.clj
  src/oc/storage/representations/activity.clj
Labels: URGENT, reviewing

#212 Code cleanup of Ziggeo callback video processing.
  README.md
  project.clj
  src/oc/storage/api/entries.clj
  src/oc/storage/api/videos.clj
  src/oc/storage/app.clj
  src/oc/storage/async/notification.clj
  src/oc/storage/config.clj
  src/oc/storage/db/migrations/1561728596998_remove_video_id_index.edn
  src/oc/storage/representations/entry.clj
  src/oc/storage/resources/entry.clj
  src/oc/storage/util/ziggeo.clj
Labels: ready for deploy

#216 Remove section picker
  src/oc/storage/api/orgs.clj
  src/oc/storage/config.clj
  src/oc/storage/representations/org.clj
Labels: reviewing
