Repository open-company/open-company-storage, pull requests merged in 2019-06, with the labels that each got.

#203 Sample post author/comment/reaction
  resources/samples/general.edn
  src/oc/storage/api/orgs.clj
Labels: reviewing

#206 Fix autoshare error
  project.clj
  src/oc/storage/api/entries.clj
  src/oc/storage/async/bot.clj
Labels: URGENT, ready for deploy

#202 Delete sample posts link fix
  project.clj
  src/oc/storage/api/orgs.clj
  src/oc/storage/resources/entry.clj
Labels: ready for deploy

#204 Public and private access in activity response
  src/oc/storage/api/activity.clj
  src/oc/storage/async/bot.clj
  src/oc/storage/async/email.clj
  src/oc/storage/representations/activity.clj
  src/oc/storage/representations/entry.clj
Labels: reviewing

#201 Fix viewer contributor access
  src/oc/storage/api/activity.clj
  src/oc/storage/api/entries.clj
  src/oc/storage/api/orgs.clj
  src/oc/storage/representations/activity.clj
  src/oc/storage/representations/board.clj
Labels: ready for deploy

#208 Post sorting
  project.clj
  src/oc/storage/api/activity.clj
  src/oc/storage/api/boards.clj
  src/oc/storage/api/entries.clj
  src/oc/storage/lib/sort.clj
  src/oc/storage/lib/timestamp.clj
  src/oc/storage/representations/activity.clj
  src/oc/storage/representations/board.clj
  src/oc/storage/representations/entry.clj
  src/oc/storage/representations/org.clj
  src/oc/storage/resources/entry.clj
  src/oc/storage/urls/board.clj
Labels: reviewing

#210 Fix reactions count
  src/oc/storage/api/boards.clj
Labels: URGENT, ready for deploy

#209 Drift → Intercom
  resources/samples/general.edn
Labels: reviewing
